In [20]:
import numpy, scipy.special, matplotlib.pyplot
print(numpy.zeros([3,3]))

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [3]:
%matplotlib inline
a = numpy.zeros([3,3,3])
a[0,1,2]=2
print(a)

[[[ 0.  0.  0.]
  [ 0.  0.  2.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]


In [19]:
class Dog:

   def __init__(self,petname,temp):
        self.name=petname
        self.temp=temp
        
   def bark(self):
       print("{}: woof [{}º]").format(self.name,self.temp)
       pass
   
   def getTemp(self):
        return(self.temp)

   def setTemp(self,newtemp):
        self.temp = newtemp
    
   pass
   
bonso = Dog('bonso',34)
bonso.bark()
print(bonso.getTemp())
bonso.setTemp(9999)
print(bonso.getTemp())

bonso: woof [34º]
34
9999


In [87]:
# OK: start a network

class neuralNetwork:
    
    #initialise
    def __init__(self, inputnodes,hiddennodes,outputnodes,learningrate):
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        self.lr = learningrate
        self.wih = numpy.random.normal(0.0,pow(self.hnodes,-0.5),(self.hnodes,self.inodes))
        self.who = numpy.random.normal(0.0,pow(self.onodes,-0.5),(self.onodes,self.hnodes))
        self.activation_function = lambda x: scipy.special.expit(x)
        pass
    
    #train it
    def train(self, inputs_list, targets_list):
        inputs = numpy.array(inputs_list, ndmin=2) .T
        targets = numpy.array(targets_list, ndmin=2) .T
        
        hidden_inputs = numpy.dot(self.wih,inputs)
        hidden_outputs = self.activation_function(hidden_inputs)

        final_inputs = numpy.dot(self.who,hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        
        #errors
        output_errors = targets - final_outputs
        hidden_errors = numpy.dot(self.who.T, output_errors)
        
        #update
        self.who += self.lr * numpy.dot((output_errors * final_outputs * (1-final_outputs)),numpy.transpose(hidden_outputs))
        self.wih += self.lr * numpy.dot((hidden_errors * hidden_outputs * (1-hidden_outputs)),numpy.transpose(inputs))
        pass
    
    #test it with data
    def query(self, inputs_list):
        inputs = numpy.array(inputs_list, ndmin=2) .T
        
        hidden_inputs = numpy.dot(self.wih,inputs)
        hidden_outputs = self.activation_function(hidden_inputs)

        final_inputs = numpy.dot(self.who,hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        
        return final_outputs
    
# do something
n = neuralNetwork(3,3,3,0.3)
n.query((1,10,100))

array([[ 0.4827751 ],
       [ 0.51046902],
       [ 0.42656971]])

In [85]:
data_file = open("/Users/joeparker/Documents/all_work/programming/python/byo_neural_network/mnist_train.csv",'r')
data_list = data_file.readlines()
data_file.close()
#data_list[0]

In [84]:
all_values = data_list[1].split(',')
img_array=numpy.asfarray(all_values[1:]).reshape((28,28))
#matplotlib.pyplot.imshow(img_array,cmap="Greys",interpolation="none")
scaled_input=(numpy.asfarray(all_values[1:]) / (255.0 * 0.99)) + 0.01
#print(scaled_input)
max(scaled_input)


1.0201010101010102

In [56]:
# output nodes
onodes = 10
targets = numpy.zeros(onodes) + 0.01
targets[int(all_values[0])]=0.99
print(targets)

[ 0.99  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01]


In [71]:
#try it 
onodes = 10
n = neuralNetwork(784,100,onodes,0.3)

# load training
# wget http://pjreddie.com/media/files/mnist_train.csv
training_data_file = open("/Users/joeparker/Documents/all_work/programming/python/byo_neural_network/mnist_train.csv",'r')
training_data_list = training_data_file.readlines()
training_data_file.close()

# train
for record in training_data_list:
    all_values = record.split(',')
    inputs = (numpy.asfarray(all_values[1:]) / (255.0 * 0.99)) + 0.01
    targets = numpy.zeros(onodes) + 0.01
    targets[int(all_values[0])]=0.99
    n.train(inputs,targets)
    pass

#load test
# wget http://pjreddie.com/media/files/mnist_test.csv
test_data_file = open("/Users/joeparker/Documents/all_work/programming/python/byo_neural_network/mnist_test.csv",'r')
test_data_list = test_data_file.readlines()
test_data_file.close()

#test once
#print(test_data_list[0].split(','))



['7', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',

In [76]:
all_values = test_data_list[0].split(',')
print(all_values[0])
n.query((numpy.asfarray(all_values[1:]) / (255.0 * 0.99)) + 0.01)

7


array([[  2.50655402e-03],
       [  3.83237352e-03],
       [  1.74379291e-02],
       [  3.59301659e-03],
       [  1.33157922e-03],
       [  1.04052597e-03],
       [  1.79511674e-03],
       [  9.90648867e-01],
       [  1.66586423e-04],
       [  2.52577347e-03]])

In [83]:
# test the performance 

scores = []

for record in test_data_list:
    all_values = record.split(',')
    answer = int(all_values[0])
    inputs = (numpy.asfarray(all_values[1:]) / (255.0 * 0.99)) + 0.01
    output = n.query(inputs)
    guess = numpy.argmax(output)
    if(guess == answer):
        scores.append(1)
    else:
        scores.append(0)
        pass
    pass

score_array = numpy.asarray(scores)
hits = score_array.sum() + 0.0
trials = score_array.size + 0.0

print("performance = ", (hits / trials))

('performance = ', 0.94479999999999997)


In [97]:
some_a = numpy.array([0,1,2], ndmin=3)
print(some_a)

[[[0 1 2]]]
